apiVersion: apps/v1
kind: Deployment
metadata:
  name: penguin-web
  namespace: penguin
spec:
  selector:
    matchLabels:
      app: penguin-web
  replicas: 2
  template:
    metadata:
      labels:
        app: penguin-web
    spec:
      containers:
        - name: penguin-web
          image: 10.105.58.187:5000/penguin-web:79
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: penguin-secret
          ports:
          - containerPort: 8081
