apiVersion: apps/v1
kind: Deployment
metadata:
  name: penguin-web
  namespace: penguin
spec:
  selector:
    matchLabels:
      app: penguin-web
  replicas: 2
  template:
    metadata:
      labels:
        app: penguin-web
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: penguin-web
          image: registry-docker-registry.registry.svc.cluster.local:5000/penguin-web:74
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
