apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: penguin-web-ingress
  namespace: penguin
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://auth.devjk.me/auth"
    # nginx.ingress.kubernetes.io/auth-signin: "https://auth.devjk.me/oauth2/start?rd=$scheme://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization,X-Auth-Request-User,X-Auth-Request-Email"
    nginx.ingress.kubernetes.io/auth-snippet: |
      auth_request_set $auth_status $upstream_status;
      if ($auth_status = 401) {
        # Ignore the 401 response and continue to proxy the request
        set $auth_status "";
      }
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: devjk.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend :
          service:
            name: penguin-web
            port:
              number: 8081
