pipeline {
    agent any
    stages {
        stage('build Jar') {
            steps {
                echo 'Building..'
                echo "${params.role}"
                sh "ls -la"
            }
        }
        stage('build Docker') {
            steps {
                echo 'Building Docker..'
            }
        }
    }
}