pipeline {
    agent any
    tools {
        'org.jenkinsci.plugins.docker.commons.tools.DockerTool' '18.09'
    }
    environment {
        DOCKER_CERT_PATH = credentials('dockerhub')
    }
    stages {
        stage('build jar') {
            steps {
                echo 'Building..'
                echo "${params.role}"
                sh "./gradlew ${params.role}:bootJar"
                sh "ls -la ./${params.role}/build/libs"
            }
        }
        stage('build image') {
            steps {
                echo 'Building Docker..'
                sh "docker build -t devjk4254/penguin ./${params.role}"
                sh "docker image push devjk4254/penguin"
            }
        }
    }
}