spring:
  profiles:
    group:
      "local": "local, common"
      "prod": "prod, common"
---
spring:
  config:
    activate:
      on-profile: "common"

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  output:
    ansi:
      enabled: always
  session:


server:
  port: 8082
  tomcat:
    threads:
      max: 200
    maxConnections: 10000
    acceptCount: 100
    maxKeepAliveRequests: 100
    connectionTimeout: 60000

redis-host: ${REDIS_HOST}
redis-port: ${REDIS_PORT}
redis-password: ${REDIS_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: "local"
  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/penguin?useSSL=false&serverTimezone=UTC&connectTimeout=5000&autoReconnect=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: "prod"
logging:
  level:
    root: debug