spring:
  profiles:
    group:
      "local": "local, common"
      "prod": "prod, common"
---
spring:
  config:
    activate:
      on-profile: "common"

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://${DB_HOST}/penguin?useSSL=false&serverTimezone=UTC&connectTimeout=5000&autoReconnect=true&allowPublicKeyRetrieval=true
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

server:
  port: 8082
  tomcat:
    threads:
      max: 200
    maxConnections: 10000
    acceptCount: 100
    maxKeepAliveRequests: 100
    connectionTimeout: 60000

db-host: ${DB_HOST}
db-username: ${DB_USERNAME}
db-password: ${DB_PASSWORD}
redis-host: ${REDIS_HOST}
redis-port: ${REDIS_PORT}
redis-password: ${REDIS_PASSWORD}
google-client-id: ${GOOGLE_CLIENT_ID}
google-client-secret: ${GOOGLE_CLIENT_SECRET}
jwt-private-key: ${JWT_PRIVATE_KEY}
jwt-public-key: ${JWT_PUBLIC_KEY}
---
spring:
  config:
    activate:
      on-profile: "local"
  devtools:
    livereload:
      enabled: true

server:
  servlet:
    session:
      cookie:
        name: devjksession
        secure: true
        http-only: true

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: "prod"

server:
  servlet:
    session:
      cookie:
        name: devjksession
        secure: true
        http-only: true
        domain: devjk.me

logging:
  level:
    root: debug